version: "3.7"

services:
  app:
    build: .
    depends_on:
    - redis
    volumes:
    - "${DOCKER_INPUT_PATH}:/volumes/input:ro"
    - "${DOCKER_OUTPUT_PATH}:/volumes/output"
    - "${DOCKER_TMP_PATH}:/volumes/tmp"
    environment:
      FLASK_APP: isimip_files_api.app
      FLASK_CONFIG: config.toml
      FLASK_BASE_URL: "http://${DOCKER_HOSTNAME}:${DOCKER_PORT}/api/v2"
      FLASK_OUTPUT_URL: "http://${DOCKER_HOSTNAME}:${DOCKER_PORT}/api/output"
      FLASK_REDIS_URL: redis://redis:6379
      FLASK_INPUT_PATH: /volumes/input
      FLASK_OUTPUT_PATH: /volumes/output
      FLASK_TMP_PATH: /volumes/tmp
    env_file: .env

  worker:
    build: .
    command: rq worker
    depends_on:
    - redis
    volumes:
    - "${DOCKER_INPUT_PATH}:/volumes/input:ro"
    - "${DOCKER_OUTPUT_PATH}:/volumes/output"
    - "${DOCKER_TMP_PATH}:/volumes/tmp"
    environment:
      FLASK_APP: isimip_files_api.app
      FLASK_CONFIG: config.toml
      FLASK_BASE_URL: "http://${DOCKER_HOSTNAME}:${DOCKER_PORT}/api/v2"
      FLASK_OUTPUT_URL: "http://${DOCKER_HOSTNAME}:${DOCKER_PORT}/api/output"
      FLASK_REDIS_URL: redis://redis:6379
      FLASK_INPUT_PATH: /volumes/input
      FLASK_OUTPUT_PATH: /volumes/output
      FLASK_TMP_PATH: /volumes/tmp
      RQ_REDIS_URL: redis://redis:6379
      RQ_WORKER_CLASS: isimip_files_api.worker.Worker
    env_file: .env

  caddy:
    image: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "${DOCKER_PORT}:80"
    volumes:
    - "${DOCKER_OUTPUT_PATH}:/volumes/output"
    - "$PWD/Caddyfile:/etc/caddy/Caddyfile"
    - "${DOCKER_CADDY_PATH}/data:/data"
    - "${DOCKER_CADDY_PATH}/config:/config"

  redis:
    image: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
    - "${DOCKER_REDIS_PATH}:/data"
    env_file: .env
